### ISSUE TITLE
Divide 24V into 12V

### ISSUE THREAD

**Issue by epvienneau** [Duke-BME-Design/Breath_of_fresh_air#102]

**Comment by epvienneau** [comment]
Might need to match impedances...

**Comment by epvienneau** [comment]
managed to roughly match impedance of circuit with 560 ohm resistors, but they got very hot. Not sure if this is ok.

**Comment by epvienneau** [comment]
is this the best way to divide the voltage @mlp6?

**Comment by mlp6** [comment]
What schematic am I looking for?

**Comment by epvienneau** [comment]
Sorry I wasn't more specific- I'm testing what it's going to be like when we have 0 to 24V from the wall instead of +12 V and -12V. I tried using two resistors of the same value to split the voltage in half and create -12V and +12V... and I did succeed but the resistors got super hot

**Comment by mlp6** [comment]
You are pulling decent current through those resistors with that config.  Might be flirting with their power rating since they aren't designed for that.  Better would be to use a virtual ground voltage regulator.

**Comment by epvienneau** [comment]
ah makes sense, didn't know that existed!

**Comment by sphaerobolus** [comment]
I have virtual grounds in Teer.
