### ISSUE TITLE
What surface mount op amps and potentiometers do you have on hand?

### ISSUE THREAD

**Issue by epvienneau** [Duke-BME-Design/Breath_of_fresh_air#104]
Need two LF353s (one of them I'm only using one side though if that makes a difference) and one INA126.

**Comment by epvienneau** [comment]
We're going to use potentiometers at first so that we don't have to make a new PCB every time we want to change a resistor (which will probably happen often).

**Comment by sphaerobolus** [comment]
I don't have a lot of SMT potentiometers on hand. I do have several SMT opamps. I can get you part numbers tomorrow (I'm at home most of today) or you can check out the opamps yourself. They're in PO5 in the beige cabinet on the left. Looking in the cabinet, they're toward the upper left. I have a couple of drawers labeled "MISC OPAMPS" and "RRIO OPAMPS"

**Comment by epvienneau** [comment]
Ok great thanks, I'll go take a look today! I'll just solder on little female headers so I can plop various resistors in for now.  Where are the voltage splitters by the way?

**Comment by sphaerobolus** [comment]
Rail splitters are outside the cabinets along the wall common with Maggie's office. Maybe in the bins with the green frame, or maybe to the left of that one. The drawer is labeled "RAIL SPLITTER", I think.
