### ISSUE TITLE
See Matt Brown about pneumotach and differential pressure sensor

### ISSUE THREAD

**Issue by dmayearg** [Duke-BME-Design/Breath_of_fresh_air#46]
From BME 354 Lab: Pneumotach  and MPX2010DP differential pressure sensor

**Comment by dmayearg** [comment]
emailed matt brown

**Comment by sarahjacobs** [comment]
Spoke to Matt - pneumotach not an option -> use some sort of fan/whistle/sail switch to ensure adequate flow post resistance.
