### ISSUE TITLE
Get the pitch of our motor rod

### ISSUE THREAD

**Issue by sarahjacobs** [Duke-BME-Design/Breath_of_fresh_air#80]
She needs it to give to Earp to make stomper. Plz find out asap and let Kayla know (I don't have the specs for the motor).

**Comment by epvienneau** [comment]
Based on the email Diana forwarded us....

**Comment by epvienneau** [comment]
<img width="338" alt="screen shot 2018-03-07 at 9 21 02 am" src="https://user-images.githubusercontent.com/31496393/37097266-f0385d26-21e8-11e8-83bb-3f36d6393c2a.png">

**Comment by epvienneau** [comment]
That's all I know right this minute, will have to do more googling to get thread size (I assume by that you mean pitch?)

**Comment by epvienneau** [comment]
@kaylawf I forwarded you the email chain, I think you should be able to go from there :)
