### ISSUE TITLE
Write Unit Testing for flow rate sensing

### ISSUE THREAD

**Issue by epvienneau** [Duke-BME-Design/Breath_of_fresh_air#82]

**Comment by epvienneau** [comment]
[MPX2010.pdf](https://github.com/Duke-BME-Design/Breath_of_fresh_air/files/1849098/MPX2010.pdf)

**Comment by epvienneau** [comment]
We are going to use this pressure sensor instead of the other one we ordered.

**Comment by dmayearg** [comment]
[pressure_testing.xlsx](https://github.com/Duke-BME-Design/Breath_of_fresh_air/files/1869106/pressure_testing.xlsx)

**Comment by epvienneau** [comment]
hysteresis is not a big deal
