### ISSUE TITLE
Design mechanism to turn blinds with motor

### ISSUE THREAD

**Issue by epvienneau** [Duke-BME-Design/Breath_of_fresh_air#89]

**Comment by dmayearg** [comment]
We have the hubs for the small motor and the bigger motor.
The larger motor has about 40 different positions (with a step size of 10) from 0 to 90 degrees. 
The smaller motor has about 17 different positions (with a step size of 5) from 0 to 90 degrees. 
The smaller motor has about 50 different positions (with a step size of 2) from 0 to 90 degrees.
