### ISSUE TITLE
Figure out how to power device without bench top supply

### ISSUE THREAD

**Issue by epvienneau** [Duke-BME-Design/Breath_of_fresh_air#92]

**Comment by dmayearg** [comment]
I bought the 24V power supply ( https://www.amazon.com/gp/product/B002LMQ6G2/ref=od_aui_detailpages00?ie=UTF8&psc=1 ) and the DC power connector from supply to GND/24V and from GND/6V to Arduino power connection 
( https://www.amazon.com/gp/product/B01LRXIILG/ref=od_aui_detailpages00?ie=UTF8&psc=1 )
